name: Build
on:
  push:
    tags:
      - 'b*-*-*'

env:
  repo: ${{ github.event.repository.name }}
  ref: ${{ github.ref_name }}
  dist_dir: ${{ github.workspace }}/dist
  # CC:   gcc-10 # use latest gcc available?
  # CXX:  g++-10 # but opus build fails with gcc 10

jobs:
  Build-Upload-Release:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        vers: ['-w', '-l']

    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build
        run: |
          python ${{ github.workspace }}/build.py ${{ matrix.vers }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.repo }}-${{ env.ref }}
          path: |
            ${{ env.dist_dir }}/*.zip
          if-no-files-found: error
          # retention-days: 60

